title: SUN BLOG
author: Ahmad Moussa
url: "https://gorillasun.de" # the base hostname & protocol for your site
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  
# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=866"
