url: "https://ahmadmoussa.github.io" # the base hostname & protocol for your site
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
